KEYWORDS = {
    "reason": [
        "analyze", "analysis", "reasoning", "reason", "logical", "logic",
        "think", "thinking", "thought", "decide", "decision", "determine",
        "infer", "inference", "conclude", "conclusion",
        "explain", "explanation", "clarify", "clarification",
        "compare", "comparison", "contrast", "evaluate", "evaluation",
        "assess", "assessment", "judge", "judgment",
        "plan", "planning", "schedule", "workflow", "process", "procedure",
        "step", "steps", "stepwise", "sequential",
        "strategy", "strategize", "approach", "method",
        "predict", "prediction", "estimate", "estimation",
        "verify", "validation", "check", "inspection"
    ],
    "code": ["code", "coding", "program", "programming", "implement", "implementation",
        "develop", "development", "build", "construct",
        "function", "functions", "method", "methods",
        "class", "classes", "object", "objects",
        "script", "scripts", "module", "modules",
        "library", "libraries", "package", "packages",
        "framework", "system", "software", "application",
        "python", "java", "javascript", "typescript", "c", "cpp", "c++", "bash", "shell",
        "compile", "compilation", "build", "deploy", "deployment",
        "run", "execute", "execution", "launch",
        "debug", "debugging", "test", "testing", "unittest",
        "error", "errors", "bug", "bugs", "fix", "patch",
        "input", "output", "parameter", "argument", "return"
    ],
    "math": ["calculate", "calculation", "compute", "computation",
        "formula", "formulas", "equation", "equations",
        "derive", "derivation", "proof", "theorem",
        "optimize", "optimization", "minimize", "maximize",
        "objective", "loss", "cost", "function",
        "probability", "probabilistic", "statistics", "statistical",
        "mean", "average", "variance", "deviation",
        "matrix", "matrices", "vector", "vectors", "tensor",
        "gradient", "derivative", "differential",
        "sum", "summation", "integral", "integrate",
        "model", "modeling", "regression", "classification",
        "approximate", "approximation", "estimation",
        "numeric", "numerical", "analytic", "analytical"
    ],
    "tool": ["api", "apis", "tool", "tools", "service", "services",
        "call", "calls", "calling", "invoke", "invocation",
        "request", "requests", "response", "responses",
        "query", "queries", "fetch", "retrieve", "retrieval",
        "search", "lookup", "find", "discover",
        "access", "connect", "connection", "interface",
        "endpoint", "endpoints", "url", "uri",
        "http", "https", "rest", "rpc",
        "database", "databases", "storage", "cache",
        "server", "client", "backend", "frontend",
        "web", "website", "webpage", "online",
        "upload", "download", "transfer", "sync",
        "authentication", "authorization", "token", "key"
    ],
    "domain": [
        "weather", "forecast", "temperature", "climate",
        "location", "address", "city", "country", "region",
        "time", "date", "day", "month", "year", "calendar", "schedule",
        "travel", "trip", "flight", "airline", "airport", "hotel", "booking",
        "map", "navigation", "route", "distance", "direction",
        "finance", "financial", "money", "payment", "price", "cost",
        "stock", "market", "trade", "trading", "exchange",
        "health", "medical", "medicine", "hospital", "patient",
        "image", "photo", "picture", "video", "audio",
        "text", "document", "file", "data", "information",
        "user", "users", "account", "profile", "record"
    ]
}